### ISSUE TITLE
Got error when start up new project with webapi + npsql

### ISSUE THREAD

**Issue by BrianLeeGH** [JJConsulting/JJMasterData#264]
**Describe the bug**
A new web api project with npsql.
Just start up program and got this error

**To Reproduce**

1. <ItemGroup>
  <PackageReference Include="JJMasterData.Web" Version="4.3.10" />
  <PackageReference Include="Npgsql" Version="4.1.14" />
  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
</ItemGroup>
2.{
  "AllowedHosts": "*",
  "JJMasterData": {
    "ConnectionString": "Host=localhost;Port=5432;Database=chathub_jj_master;User ID=aaa;Password=aaa;",
    "DataDictionaryTableName": "tb_masterdata",
    "LocalizationTableName": "tb_masterdata_localization",
    "ReadProcedurePattern": "{tablename}Get",
    "WriteProcedurePattern": "{tablename}Set",
    "ConnectionProvider": "PostgreSql"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  }
}
![image](https://github.com/user-attachments/assets/f2fc1cf3-1d22-4a3f-aa0e-64648c3fe9c3)
3.Click run from VS 2022

**.NET version**
[.Net 8]

**Additional context**
 Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
         at JJMasterData.Commons.Data.DataAccess.TableExistsAsync(String tableName, CancellationToken cancellationToken)
         at JJMasterData.Commons.Logging.Db.DbLoggerBackgroundService.LogAsync(LogMessage entry, CancellationToken cancellationToken)
         at JJMasterData.Commons.Logging.LoggerBackgroundService`1.ExecuteAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
         at JJMasterData.Commons.Data.DataAccess.TableExistsAsync(String tableName, CancellationToken cancellationToken)
         at JJMasterData.Commons.Logging.Db.DbLoggerBackgroundService.LogAsync(LogMessage entry, CancellationToken cancellationToken)
         at JJMasterData.Commons.Logging.LoggerBackgroundService`1.ExecuteAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundServ

**Comment by gumbarros** [comment]
Unfortunately PostgreSQL is not supported yet. 

https://github.com/JJConsulting/JJMasterData/tree/main/src/Commons/Data/Entity/Providers

This how you implement a DB provider. But we are thinking in improving this via DI like EF does.
