### ISSUE TITLE
BackgroundService Failure Due to DataAccessException Cannot open database "JJMasterData"

### ISSUE THREAD

**Issue by souvikk27** [JJConsulting/JJMasterData#265]
Whenever I'm trying to run the project I'm getting this exception. I'm using sql server authentication with valid credentials.

Microsoft.Extensions.Hosting.Internal.Host[9]
BackgroundService failed
JJMasterData.Commons.Exceptions.DataAccessException: Cannot open database "JJMasterData" requested by the login. The login failed.
Login failed for user 'DESKTOP-TNVIPG5\SOUVIK'.
   at JJMasterData.Commons.Data.DataAccess.GetResultAsync(DataAccessCommand cmd, CancellationToken cancellationToken) in D:\Code\NET\master-data\JJMasterData\src\Commons\Data\DataAccessAsync.cs:line 146
   at JJMasterData.Commons.Data.DataAccess.TableExistsAsync(String tableName, CancellationToken cancellationToken) in D:\Code\NET\master-data\JJMasterData\src\Commons\Data\DataAccessAsync.cs:line 328
   at JJMasterData.Commons.Logging.Db.DbLoggerBackgroundService.LogAsync(LogMessage entry, CancellationToken cancellationToken) in D:\Code\NET\master-data\JJMasterData\src\Commons\Logging\Db\DbLoggerBackgroundService.cs:line 29
   at JJMasterData.Commons.Logging.LoggerBackgroundService`1.ExecuteAsync(CancellationToken cancellationToken) in D:\Code\NET\master-data\JJMasterData\src\Commons\Logging\LoggerBackgroundService.cs:line 16
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)

**Comment by gumbarros** [comment]
Hello @souvikk27, your SQL connection is invalid. Please check your connection string at appsettings.json. I recommend to copying and pasting the string at Azure Data Studio.
